//! README.md generation

use crate::types::DatasetSummary;

/// Generate a README.md file for a dataset
///
/// Creates a template README with standard sections and placeholders
/// for information that must be filled in manually.
pub fn generate_readme(summary: &DatasetSummary) -> String {
    let mut content = String::new();

    // Title
    content.push_str("# [TODO: Dataset Title]\n\n");

    // Description
    content.push_str("## Description\n\n");
    content.push_str("[TODO: Provide a brief description of this dataset, including its purpose, scope, and scientific context]\n\n");

    // Contents
    content.push_str("## Contents\n\n");
    content.push_str(&format!(
        "This dataset contains {} files totaling {}:\n\n",
        summary.total_files,
        summary.format_size()
    ));

    for (file_type, count) in &summary.file_type_counts {
        content.push_str(&format!("- {} {} files\n", count, file_type));
    }
    content.push('\n');

    // Data Files
    content.push_str("## Data Files\n\n");
    content.push_str("[TODO: Describe each data file and its contents]\n\n");

    // Usage
    content.push_str("## Usage\n\n");
    content.push_str("[TODO: Describe how to use this data, including:\n");
    content.push_str("- Required software or tools\n");
    content.push_str("- Data format specifications\n");
    content.push_str("- Example analysis workflows\n");
    content.push_str("- Known limitations or caveats]\n\n");

    // Citation
    content.push_str("## Citation\n\n");
    content.push_str("[TODO: Provide citation information for this dataset]\n\n");
    content.push_str("Example format:\n");
    content.push_str("```\n");
    content.push_str("Author(s). (Year). Dataset Title. Publisher/Repository. DOI or URL\n");
    content.push_str("```\n\n");

    // License
    content.push_str("## License\n\n");
    content.push_str("[TODO: Specify the license under which this data is released]\n\n");

    // Contact
    content.push_str("## Contact\n\n");
    content.push_str("[TODO: Provide contact information for questions or issues]\n\n");

    // Footer
    content.push_str("---\n");
    content.push_str(&format!(
        "Generated by genesis-preflight v0.1.0 on {}\n",
        summary.scan_timestamp
    ));
    content.push_str("Review and complete all [TODO] sections before publication.\n");

    content
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_readme() {
        let mut summary = DatasetSummary::new();
        summary.total_files = 5;
        summary.total_size = 1024 * 1024; // 1 MB
        summary.scan_timestamp = "2024-01-15 12:00:00 UTC".to_string();

        let content = generate_readme(&summary);

        assert!(content.contains("# [TODO: Dataset Title]"));
        assert!(content.contains("## Description"));
        assert!(content.contains("## Contents"));
        assert!(content.contains("5 files"));
        assert!(content.contains("## Usage"));
        assert!(content.contains("## Citation"));
        assert!(content.contains("## License"));
        assert!(content.contains("## Contact"));
        assert!(content.contains("genesis-preflight"));
    }

    #[test]
    fn test_readme_has_todos() {
        let summary = DatasetSummary::new();
        let content = generate_readme(&summary);

        // Verify all sections have TODO markers
        assert!(content.contains("[TODO:"));
    }
}
